---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Jekyll configuration for GitHub Pages
title: "Gerrit Reports - Linux Foundation"
description: "Automated reports on Linux Foundation Gerrit servers and projects"
baseurl: "/gerrit-reports"
url: "https://modeseven-lfit.github.io"

# Repository information
repository: "modeseven-lfit/gerrit-reports"

# GitHub Pages settings
github_username: modeseven-lfit
github:
  repository_url: https://github.com/modeseven-lfit/gerrit-reports

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - .github/
  - .gitignore
  - .gitlint
  - .pre-commit-config.yaml
  - .readthedocs.yml
  - .yamllint
  - LICENSES/
  - LICENSE
  - "*.md"

# Include files that would normally be excluded
include:
  - README.md

# Collections and defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Kramdown settings
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# SEO settings
author:
  name: "Linux Foundation"
  email: "lf-releng@linuxfoundation.org"

# Social settings
twitter:
  username: linuxfoundation

# Analytics (if needed)
google_analytics: # Add GA tracking ID if needed

# Custom variables
lf:
  project_reports_repo: "https://github.com/modeseven-lfit/project-reports"
  main_site: "https://www.linuxfoundation.org"
